Repository asapdiscovery/asapdiscovery, pull requests merged in 2022-11, with the labels that each got.

#58 split up protein prep and use SEQRES to make mutations
  cluster_scripts/fauxalysis_from_docking.sh
  cluster_scripts/prep_proteins.sh
  covid_moonshot_ml/data/openeye.py
  covid_moonshot_ml/datasets/pdb.py
  covid_moonshot_ml/datasets/utils.py
  covid_moonshot_ml/docking/docking.py
  covid_moonshot_ml/modeling.py
  covid_moonshot_ml/schema.py
  data/mers-structures-dimers.yaml
  data/mers-structures.yaml
  data/mpro_mers_seqres.yaml
  data/mpro_sars2_seqres.yaml
  scripts/filter_fragalysis_by_smarts.py
  scripts/find_all_mcs.py
  scripts/hallucinate_fragalysis.py
  scripts/make_docked_complexes.py
  scripts/mass_add_seqres.py
  scripts/mcs_res_mpro_to_compound.py
  scripts/prep_fragalysis_dus.py
  scripts/prep_pdb_structures.py
  scripts/prep_proteins.py
  scripts/run_docking_oe.py
  scripts/test-protein-prep.py
Labels: priority: high, ready to be merged

#65 Update fauxalysis script
  cluster_scripts/clean_results_csv.sh
  covid_moonshot_ml/data/__init__.py
  covid_moonshot_ml/data/openeye.py
  covid_moonshot_ml/docking/analysis.py
  data/cmpd_to_frag.yaml
  data/datasets.yaml
  notebook/test-dataframe-manipulation.ipynb
  scripts/clean_results_csv.py
  scripts/create_fauxalysis_subset_from_yaml.py
  scripts/fauxalysis_from_docking.py
  scripts/hallucinate_fragalysis.py
  scripts/prep_carlsson_pdbs.py
  scripts/write_cmpd_to_frag_dict.py
Labels: priority: high

#82 Update moonshot downloading and filtering
  covid_moonshot_ml/datasets/moonshot.py
  covid_moonshot_ml/datasets/utils.py
  scripts/download_moonshot_data.py
Labels: ready for review

#81 Add 2d graph models
  .github/workflows/CI.yaml
  covid_moonshot_ml/data/dataset.py
  covid_moonshot_ml/nn/models/GAT.py
  covid_moonshot_ml/nn/models/__init__.py
  covid_moonshot_ml/utils.py
  scripts/train.py
Labels: ready for review

#33 Add loss function class to handle step and uncertainty loss functions
  covid_moonshot_ml/data/dataset.py
  covid_moonshot_ml/data/openeye.py
  covid_moonshot_ml/datasets/utils.py
  covid_moonshot_ml/nn/__init__.py
  covid_moonshot_ml/nn/loss/GaussianNLLLoss.py
  covid_moonshot_ml/nn/loss/MSELoss.py
  covid_moonshot_ml/nn/loss/__init__.py
  covid_moonshot_ml/utils.py
  scripts/hallucinate_fragalysis.py
  scripts/plot_docking_results.py
  scripts/train.py
  scripts/upset_plot_ranked.py
Labels: ready for review
