Repository asapdiscovery/asapdiscovery, pull requests merged in 2023-08, with the labels that each got.

#420 Add functionality for downloading/parsing Mac1 data from CDD
  asapdiscovery-data/asapdiscovery/data/moonshot.py
  asapdiscovery-data/asapdiscovery/data/scripts/download_moonshot_data.py
  asapdiscovery-data/asapdiscovery/data/tests/test_moonshot.py
  asapdiscovery-data/asapdiscovery/data/utils.py
Labels: ready for review

#422 Fix for GIF viz so that pocket is coloured correctly
  asapdiscovery-dataviz/asapdiscovery/dataviz/gif_viz.py
  asapdiscovery-simulation/asapdiscovery/simulation/simulate.py
Labels: tiny, visualisation

#419 Improve loss tracking
  asapdiscovery-ml/asapdiscovery/ml/scripts/plot_data_efficiency.py
  asapdiscovery-ml/asapdiscovery/ml/scripts/train.py
  asapdiscovery-ml/asapdiscovery/ml/utils.py
Labels: ready for review

#427 Don't log (potentially) confidential info
  asapdiscovery-ml/asapdiscovery/ml/scripts/train.py
Labels: ready for review, tiny

#429 Add FragalysisFactory schema
  asapdiscovery-data/asapdiscovery/data/schema_v2/complex.py
  asapdiscovery-data/asapdiscovery/data/schema_v2/fragalysis.py
  asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml
  asapdiscovery-data/asapdiscovery/data/tests/test_complex_schema_v2.py
  asapdiscovery-data/asapdiscovery/data/tests/test_fragalysis_factory_schema_v2.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/calculate_RMSD_of_docked_ligands.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/make_docked_complexes.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/score_structures.py
  asapdiscovery-modeling/asapdiscovery/modeling/modeling.py
  asapdiscovery-modeling/asapdiscovery/modeling/tests/test_modeling_utils.py
  asapdiscovery-modeling/asapdiscovery/modeling/tests/test_protein_prep.py
Labels: ready for review
