Repository asapdiscovery/asapdiscovery, pull requests merged in 2023-06, with the labels that each got.

#272 Convert protein prep tests to be pythonic
  .github/workflows/CI.yaml
  asapdiscovery-data/asapdiscovery/data/openeye.py
  asapdiscovery-data/asapdiscovery/data/schema.py
  asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml
  asapdiscovery-data/asapdiscovery/data/utils.py
  asapdiscovery-docking/asapdiscovery/docking/analysis.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/calculate_RMSD_of_docked_ligands.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/fauxalysis_from_docking.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/make_docked_complexes.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/run_docking_oe.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/score_structures.py
  asapdiscovery-modeling/asapdiscovery/modeling/modeling.py
  asapdiscovery-modeling/asapdiscovery/modeling/schema.py
  asapdiscovery-modeling/asapdiscovery/modeling/scripts/prep_fragalysis_dus.py
  asapdiscovery-modeling/asapdiscovery/modeling/scripts/prep_proteins_v2.py
  asapdiscovery-modeling/asapdiscovery/modeling/scripts/prepare_protein_csv.py
  asapdiscovery-modeling/asapdiscovery/modeling/scripts/split_oedu_and_save.py
  asapdiscovery-modeling/asapdiscovery/modeling/tests/conftest.py
  asapdiscovery-modeling/asapdiscovery/modeling/tests/mpro_fragalysis_seqres_addition_test.py
  asapdiscovery-modeling/asapdiscovery/modeling/tests/prep_mers_rcsb/cif1_to_prepped_du_test.py
  asapdiscovery-modeling/asapdiscovery/modeling/tests/prep_sars_fragalysis/README.txt
  asapdiscovery-modeling/asapdiscovery/modeling/tests/prep_sars_fragalysis/prep_mpro_test.sh
  asapdiscovery-modeling/asapdiscovery/modeling/tests/test_modeling_utils.py
  asapdiscovery-modeling/asapdiscovery/modeling/tests/test_prep_proteins_v2/test_prep_proteins_v2.sh
  asapdiscovery-modeling/asapdiscovery/modeling/tests/test_prepare_protein_csv/aligned/Mpro-P2660_0A/Mpro-P2660_0A_bound.pdb
  asapdiscovery-modeling/asapdiscovery/modeling/tests/test_prepare_protein_csv/metadata.csv
  asapdiscovery-modeling/asapdiscovery/modeling/tests/test_prepare_protein_csv/test_prepare_protein_csv.sh
  asapdiscovery-modeling/asapdiscovery/modeling/tests/test_prepare_protein_csv/to_prep.csv
  asapdiscovery-modeling/asapdiscovery/modeling/tests/test_protein_prep.py
  asapdiscovery-modeling/asapdiscovery/modeling/tests/test_schema.py
  asapdiscovery-simulation/asapdiscovery/simulation/schema.py
  asapdiscovery-simulation/asapdiscovery/simulation/tests/test_forcefield_generation.py
  asapdiscovery-simulation/asapdiscovery/simulation/utils.py
Labels: enhancement, ready for review, testing

#247 Improve docking analysis visualization
  asapdiscovery-dataviz/asapdiscovery/dataviz/scripts/dash_all_results_exploration.py
  asapdiscovery-dataviz/asapdiscovery/dataviz/scripts/dash_docking_contour_plot.py
  asapdiscovery-dataviz/asapdiscovery/dataviz/scripts/dash_docking_interactive_scatterplots.py
Labels: ready for review, tiny

#291 add split-sdf-to-pyproject-toml
  asapdiscovery-data/pyproject.toml
Labels: ready for review, tiny

#92 Add code for analyzing docking results
  asapdiscovery-data/asapdiscovery/data/notebooks/test_sdf_filtering.ipynb
  asapdiscovery-data/asapdiscovery/data/utils.py
  asapdiscovery-docking/asapdiscovery/docking/analysis.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/clean_results_csv.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/fauxalysis_from_best_results_csv.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/fauxalysis_from_docking.py
Labels: ready for review

#295 unskip rmsd calculation test
  asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml
  asapdiscovery-docking/asapdiscovery/docking/tests/test_rmsd_calculation.py
Labels: testing

#325 remove analysis notebooks
  asapdiscovery-modeling/asapdiscovery/modeling/notebooks/active-site-analysis.ipynb
  asapdiscovery-modeling/asapdiscovery/modeling/notebooks/fragalysis-chemical-diversity.ipynb
  asapdiscovery-modeling/asapdiscovery/modeling/notebooks/fragalysis-structural-diversity.ipynb
  asapdiscovery-modeling/asapdiscovery/modeling/notebooks/test-n-to-n-rmsd-calculation.ipynb
  asapdiscovery-modeling/asapdiscovery/modeling/notebooks/test-n-to-n-tanimoto-combo.ipynb
Labels: ready for review, ready to be merged, tiny

#332 Add SchNet pIC50 output
  asapdiscovery-ml/asapdiscovery/ml/inference/inference.py
Labels: ready for review, ready to be merged, ml, tiny

#330 Add read id from smiles file
  asapdiscovery-data/asapdiscovery/data/scripts/sdf_to_smiles_list.py
  asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml
  asapdiscovery-data/asapdiscovery/data/tests/conftest.py
  asapdiscovery-data/asapdiscovery/data/tests/test_openeye_file_parsing.py
  asapdiscovery-data/asapdiscovery/data/utils.py
  asapdiscovery-data/pyproject.toml
Labels: ready for review, ready to be merged, docking, testing

#246 Project support docking
  .github/workflows/CI.yaml
  asapdiscovery-data/asapdiscovery/data/execution_utils.py
  asapdiscovery-data/asapdiscovery/data/logging.py
  asapdiscovery-data/asapdiscovery/data/openeye.py
  asapdiscovery-data/asapdiscovery/data/scripts/sdf_to_smiles_list.py
  asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml
  asapdiscovery-data/asapdiscovery/data/tests/conftest.py
  asapdiscovery-data/asapdiscovery/data/tests/test_openeye_file_parsing.py
  asapdiscovery-data/asapdiscovery/data/utils.py
  asapdiscovery-data/pyproject.toml
  asapdiscovery-dataviz/asapdiscovery/dataviz/_gif_blocks.py
  asapdiscovery-dataviz/asapdiscovery/dataviz/_html_blocks.py
  asapdiscovery-dataviz/asapdiscovery/dataviz/gif_viz.py
  asapdiscovery-dataviz/asapdiscovery/dataviz/html_viz.py
  asapdiscovery-dataviz/asapdiscovery/dataviz/resources/OpenSans-Regular.ttf
  asapdiscovery-dataviz/asapdiscovery/dataviz/resources/fonts.py
  asapdiscovery-dataviz/asapdiscovery/dataviz/show_contacts.py
  asapdiscovery-docking/asapdiscovery/docking/docking.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/dock_small_scale_end_to_end.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/run_docking_oe.py
  asapdiscovery-docking/asapdiscovery/docking/tests/conftest.py
  asapdiscovery-docking/asapdiscovery/docking/tests/test_docking.py
  asapdiscovery-docking/pyproject.toml
  asapdiscovery-simulation/asapdiscovery/simulation/simulate.py
  devtools/conda-envs/asapdiscovery.yaml
Labels: ready for review, docking

#335 Change Filelogger default level to WARNING
  asapdiscovery-data/asapdiscovery/data/logging.py
  asapdiscovery-data/asapdiscovery/data/tests/test_logging.py
Labels: ready for review, ready to be merged, tiny

#336 Allow openeye loading and saving functions to take str or Path, and improve typing.
  asapdiscovery-data/asapdiscovery/data/openeye.py
Labels: ready for review, ready to be merged, refactor, small
