Repository asapdiscovery/asapdiscovery, pull requests merged in 2023-10, with the labels that each got.

#493 Separate workflows/CI for subpackages
  .github/workflows/alchemy.yaml
  .github/workflows/data.yaml
  .github/workflows/dataviz.yaml
  .github/workflows/docking.yaml
  .github/workflows/macos-ci.yaml
  .github/workflows/ml.yaml
  .github/workflows/modeling.yaml
  .github/workflows/simulation.yaml
Labels: ready for review, testing

#484 swap to using high-level gifsicle api
  asapdiscovery-dataviz/asapdiscovery/dataviz/gif_viz.py
Labels: ready to be merged

#483 Fix gif test
  asapdiscovery-dataviz/asapdiscovery/dataviz/tests/test_gif_viz.py
Labels: ready for review

#511 Add fitness interactions
  asapdiscovery-dataviz/asapdiscovery/dataviz/html_viz.py
Labels: refactor

#503 Remove annoying files and logs
  asapdiscovery-data/asapdiscovery/data/tests/test_logging.py
Labels: tiny

#518 Remove OE logging in docking
  asapdiscovery-docking/asapdiscovery/docking/docking.py
Labels: bug, tiny

#528 Add ability to run inference directly on OEMol
  asapdiscovery-docking/asapdiscovery/docking/docking.py
  asapdiscovery-ml/asapdiscovery/ml/inference/inference.py
  asapdiscovery-ml/asapdiscovery/ml/tests/test_inference.py
Labels: enhancement, ready for review, small

#537 Fix MD upload for simulations that are not attempted.
  asapdiscovery-data/asapdiscovery/data/postera/manifold_artifacts.py
Labels: bug

#540 Adjust molecule filtering to make more sense
  asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml
  asapdiscovery-data/asapdiscovery/data/utils.py
Labels: ready for review, small

#523 Rework large scale docking
  asapdiscovery-data/asapdiscovery/data/dask_utils.py
  asapdiscovery-data/asapdiscovery/data/postera/manifold_data_tags.yaml
  asapdiscovery-data/asapdiscovery/data/postera/molecule_set.py
  asapdiscovery-data/asapdiscovery/data/postera/postera_factory.py
  asapdiscovery-data/asapdiscovery/data/postera/postera_uploader.py
  asapdiscovery-data/asapdiscovery/data/schema_v2/complex.py
  asapdiscovery-data/asapdiscovery/data/schema_v2/fragalysis.py
  asapdiscovery-data/asapdiscovery/data/schema_v2/ligand.py
  asapdiscovery-data/asapdiscovery/data/schema_v2/schema_base.py
  asapdiscovery-data/asapdiscovery/data/schema_v2/structure_dir.py
  asapdiscovery-data/asapdiscovery/data/selectors/mcs_selector.py
  asapdiscovery-data/asapdiscovery/data/selectors/selector.py
  asapdiscovery-data/asapdiscovery/data/testing/test_files.yaml
  asapdiscovery-data/asapdiscovery/data/tests/test_fragalysis_factory_schema_v2.py
  asapdiscovery-data/asapdiscovery/data/tests/test_openeye.py
  asapdiscovery-data/asapdiscovery/data/tests/test_selectors.py
  asapdiscovery-data/asapdiscovery/data/tests/test_structure_dir_factory_schema_v2.py
  asapdiscovery-data/asapdiscovery/data/utils.py
  asapdiscovery-docking/asapdiscovery/docking/cli.py
  asapdiscovery-docking/asapdiscovery/docking/docking_data_validation.py
  asapdiscovery-docking/asapdiscovery/docking/docking_v2.py
  asapdiscovery-docking/asapdiscovery/docking/scorer_v2.py
  asapdiscovery-docking/asapdiscovery/docking/tests/cli/cache.bin
  asapdiscovery-docking/asapdiscovery/docking/tests/cli/conftest.py
  asapdiscovery-docking/asapdiscovery/docking/tests/cli/test_cli.py
  asapdiscovery-docking/asapdiscovery/docking/tests/test_docking_v2.py
  asapdiscovery-docking/asapdiscovery/docking/workflows/large_scale_docking.py
  asapdiscovery-docking/pyproject.toml
  asapdiscovery-ml/asapdiscovery/ml/models/ml_models.py
  asapdiscovery-modeling/asapdiscovery/modeling/protein_prep_v2.py
  asapdiscovery-modeling/asapdiscovery/modeling/tests/test_protein_prep_v2.py
Labels: refactor
