Repository asapdiscovery/asapdiscovery, pull requests merged in 2023-04, with the labels that each got.

#198 Generalize ML dataset parsing
  asapdiscovery-data/asapdiscovery/data/utils.py
  asapdiscovery-ml/asapdiscovery/ml/scripts/train.py
  asapdiscovery-ml/asapdiscovery/ml/utils.py
Labels: ready for review, ml

#208 Python 3.9, 3.10 official support
  README.md
  asapdiscovery-data/pyproject.toml
  asapdiscovery-dataviz/pyproject.toml
  asapdiscovery-docking/pyproject.toml
  asapdiscovery-ml/pyproject.toml
  asapdiscovery-modeling/pyproject.toml
  asapdiscovery-simulation/pyproject.toml
Labels: ready to be merged, software

#130 Improve CDD filtering
  asapdiscovery-data/asapdiscovery/data/scripts/cdd_to_schema.py
  asapdiscovery-data/asapdiscovery/data/scripts/download_moonshot_data.py
  asapdiscovery-data/asapdiscovery/data/utils.py
Labels: ready for review

#218 Add docking timeout
  asapdiscovery-docking/asapdiscovery/docking/scripts/run_docking_oe.py
Labels: ready for review, docking

#220 Add temporal split
  asapdiscovery-data/asapdiscovery/data/moonshot.py
  asapdiscovery-data/asapdiscovery/data/schema.py
  asapdiscovery-data/asapdiscovery/data/utils.py
  asapdiscovery-ml/asapdiscovery/ml/dataset.py
  asapdiscovery-ml/asapdiscovery/ml/es.py
  asapdiscovery-ml/asapdiscovery/ml/scripts/build_dataset.py
  asapdiscovery-ml/asapdiscovery/ml/scripts/train.py
  asapdiscovery-ml/asapdiscovery/ml/utils.py
Labels: ready for review, ml

#213 Try to fix some docking memory issues
  asapdiscovery-data/asapdiscovery/data/scripts/split_sdf.py
  asapdiscovery-dataviz/pyproject.toml
  asapdiscovery-docking/asapdiscovery/docking/cluster_scripts/run_fragalysis_retrospective.sh
  asapdiscovery-docking/asapdiscovery/docking/cluster_scripts/run_fragalysis_retrospective_array.sh
  asapdiscovery-docking/asapdiscovery/docking/docking.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/run_docking_oe.py
  asapdiscovery-docking/asapdiscovery/docking/tests/test_retro_docking.sh
  asapdiscovery-docking/pyproject.toml
  devtools/conda-envs/asapdiscovery.yaml
Labels: ready for review

#231 Migrate GAT model
  asapdiscovery-ml/asapdiscovery/ml/__init__.py
  asapdiscovery-ml/asapdiscovery/ml/inference/inference.py
  asapdiscovery-ml/asapdiscovery/ml/models/GAT.py
  asapdiscovery-ml/asapdiscovery/ml/models/__init__.py
  asapdiscovery-ml/asapdiscovery/ml/scripts/train.py
  asapdiscovery-ml/asapdiscovery/ml/utils.py
  devtools/conda-envs/asapdiscovery.yaml
Labels: ready for review, ml

#240 Put val split after training split for temporal splitting
  asapdiscovery-ml/asapdiscovery/ml/utils.py
Labels: ml, tiny
