Repository asapdiscovery/asapdiscovery, pull requests merged in 2023-05, with the labels that each got.

#105 Add some initial scripts and notebooks for structure and ligand diversity analysis
  asapdiscovery-data/asapdiscovery/data/openeye.py
  asapdiscovery-data/asapdiscovery/data/schema.py
  asapdiscovery-data/asapdiscovery/data/scripts/sdf_to_smiles_list.py
  asapdiscovery-data/asapdiscovery/data/utils.py
  asapdiscovery-dataviz/asapdiscovery/dataviz/graphs.py
  asapdiscovery-dataviz/asapdiscovery/dataviz/molecules.py
  asapdiscovery-dataviz/asapdiscovery/dataviz/scripts/dash_docking_contour_plot.py
  asapdiscovery-dataviz/asapdiscovery/dataviz/scripts/dash_docking_interactive_scatterplots.py
  asapdiscovery-dataviz/asapdiscovery/dataviz/scripts/display_aligned_2d_molecules.py
  asapdiscovery-dataviz/pyproject.toml
  asapdiscovery-docking/asapdiscovery/docking/docking.py
  asapdiscovery-docking/asapdiscovery/docking/mcs.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/hallucinate_fragalysis.py
  asapdiscovery-modeling/asapdiscovery/modeling/cluster_scripts/save_mdtraj_split_fragalysis_structures.sh
  asapdiscovery-modeling/asapdiscovery/modeling/modeling.py
  asapdiscovery-modeling/asapdiscovery/modeling/notebooks/active-site-analysis.ipynb
  asapdiscovery-modeling/asapdiscovery/modeling/notebooks/fragalysis-chemical-diversity.ipynb
  asapdiscovery-modeling/asapdiscovery/modeling/notebooks/fragalysis-structural-diversity.ipynb
  asapdiscovery-modeling/asapdiscovery/modeling/notebooks/test-different-toolkits-for-loading-cif.ipynb
  asapdiscovery-modeling/asapdiscovery/modeling/notebooks/test-n-to-n-rmsd-calculation.ipynb
  asapdiscovery-modeling/asapdiscovery/modeling/notebooks/test-n-to-n-tanimoto-combo.ipynb
  asapdiscovery-modeling/asapdiscovery/modeling/scripts/prep_pdb_structures.py
  asapdiscovery-modeling/asapdiscovery/modeling/scripts/slice_fragalysis_structures_with_mdtraj.py
  asapdiscovery-modeling/pyproject.toml
Labels: science, ready for review

#255 Add Mac1 Fragalysis download
  asapdiscovery-data/asapdiscovery/data/fragalysis.py
  asapdiscovery-data/asapdiscovery/data/scripts/download_fragalysis_data.py
  asapdiscovery-data/asapdiscovery/data/tests/test_fragalysis.py
Labels: ready for review

#245 Add early stopping based on loss convergence
  asapdiscovery-ml/asapdiscovery/ml/__init__.py
  asapdiscovery-ml/asapdiscovery/ml/es.py
  asapdiscovery-ml/asapdiscovery/ml/scripts/train.py
  asapdiscovery-ml/asapdiscovery/ml/utils.py
Labels: enhancement, ml
