Repository asapdiscovery/asapdiscovery, pull requests merged in 2023-03, with the labels that each got.

#160 Fix combining crystallographic protein structure and docked ligand SDF file
  asapdiscovery-data/asapdiscovery/data/openeye.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/make_docked_complexes.py
Labels: ready for review

#159 Added AWS S3 push interface
  asapdiscovery-data/asapdiscovery/data/aws/cli.py
  asapdiscovery-data/asapdiscovery/data/aws/s3.py
  asapdiscovery-data/asapdiscovery/data/cli.py
  asapdiscovery-data/asapdiscovery/data/postera/cli.py
  asapdiscovery-data/asapdiscovery/data/tests/aws/conftest.py
  asapdiscovery-data/asapdiscovery/data/tests/aws/test_aws_cli.py
  asapdiscovery-data/asapdiscovery/data/tests/aws/test_aws_s3.py
  asapdiscovery-data/pyproject.toml
  devtools/conda-envs/test.yaml
Labels: ready for review, software

#150 Add scripts entry points for subpackages
  asapdiscovery-data/asapdiscovery/data/scripts/cdd_to_schema.py
  asapdiscovery-data/asapdiscovery/data/scripts/create_mers_schema.py
  asapdiscovery-data/asapdiscovery/data/scripts/docking_data_to_csv.py
  asapdiscovery-data/asapdiscovery/data/scripts/download_fragalysis_data.py
  asapdiscovery-data/asapdiscovery/data/scripts/download_moonshot_data.py
  asapdiscovery-data/asapdiscovery/data/scripts/filter_fragalysis_by_smarts.py
  asapdiscovery-data/asapdiscovery/data/scripts/write_cmpd_to_frag_dict.py
  asapdiscovery-data/pyproject.toml
  asapdiscovery-dataviz/asapdiscovery/dataviz/scripts/dash_all_results_exploration.py
  asapdiscovery-dataviz/asapdiscovery/dataviz/scripts/dash_docking_contour_plot.py
  asapdiscovery-dataviz/asapdiscovery/dataviz/scripts/dash_docking_exploration.py
  asapdiscovery-dataviz/asapdiscovery/dataviz/scripts/dash_docking_interactive_scatterplots.py
  asapdiscovery-dataviz/asapdiscovery/dataviz/scripts/dash_docking_interactive_table.py
  asapdiscovery-dataviz/pyproject.toml
  asapdiscovery-docking/asapdiscovery/docking/scripts/clean_results_csv.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/create_fauxalysis_subset_from_yaml.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/fauxalysis_from_docking.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/find_all_mcs.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/find_mcs_mers.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/hallucinate_fragalysis.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/make_docked_complexes.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/mass_add_seqres.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/mcs_res_mpro_to_compound.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/plot_docking_results.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/prep_fragalysis_dus.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/prep_pdb_structures.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/prep_proteins.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/run_docking_oe.py
  asapdiscovery-docking/asapdiscovery/docking/scripts/test_protein_prep.py
  asapdiscovery-docking/pyproject.toml
  asapdiscovery-ml/asapdiscovery/ml/scripts/train.py
  asapdiscovery-ml/pyproject.toml
  asapdiscovery-modeling/pyproject.toml
  devtools/scripts/create_conda_env.py
Labels: ready for review

#171 Add logging utilities and note about how to capture openeye logs
  asapdiscovery-data/asapdiscovery/data/logging.py
Labels: ready for review

#172 Merge ML dev
  asapdiscovery-ml/asapdiscovery/ml/__init__.py
  asapdiscovery-ml/asapdiscovery/ml/dataset.py
  asapdiscovery-ml/asapdiscovery/ml/es.py
  asapdiscovery-ml/asapdiscovery/ml/loss/MSELoss.py
  asapdiscovery-ml/asapdiscovery/ml/models/E3NNBind.py
  asapdiscovery-ml/asapdiscovery/ml/models/GAT.py
  asapdiscovery-ml/asapdiscovery/ml/models/SchNetBind.py
  asapdiscovery-ml/asapdiscovery/ml/models/__init__.py
  asapdiscovery-ml/asapdiscovery/ml/scripts/start_resume_sweep.sh
  asapdiscovery-ml/asapdiscovery/ml/scripts/train.py
  asapdiscovery-ml/asapdiscovery/ml/utils.py
  devtools/conda-envs/asapdiscovery.yaml
Labels: ready for review

#193 Improve dataset splitting
  asapdiscovery-ml/asapdiscovery/ml/scripts/train.py
  asapdiscovery-ml/asapdiscovery/ml/utils.py
Labels: bug, enhancement, ready for review, ml
