Repository asapdiscovery/asapdiscovery, pull requests merged in 2023-11, with the labels that each got.

#579 Fix logging error in run_openeye_oe
  asapdiscovery-docking/asapdiscovery/docking/scripts/run_docking_oe.py
Labels: bug, ready for review, tiny

#580 add mamba requirement to main readme
  README.md
Labels: documentation, ready for review, tiny

#581 delete old rmsd calculation functions
  asapdiscovery-data/asapdiscovery/data/utils.py
Labels: documentation, ready for review, software, tiny

#586 Rename moonshot module to cdd
  asapdiscovery-data/asapdiscovery/data/cdd.py
  asapdiscovery-data/asapdiscovery/data/scripts/download_cdd_data.py
  asapdiscovery-data/asapdiscovery/data/tests/test_cdd_download.py
Labels: reorganization, ready for review, small

#594 Enable simpler docking workflow using composable parts
  asapdiscovery-docking/asapdiscovery/docking/cli.py
  asapdiscovery-docking/asapdiscovery/docking/docking_v2.py
  asapdiscovery-docking/asapdiscovery/docking/openeye.py
  asapdiscovery-docking/asapdiscovery/docking/tests/cli/test_docking_cli.py
  asapdiscovery-docking/asapdiscovery/docking/tests/conftest.py
  asapdiscovery-docking/asapdiscovery/docking/tests/test_docking_v2.py
  asapdiscovery-docking/asapdiscovery/docking/workflows/cross_docking.py
  asapdiscovery-docking/asapdiscovery/docking/workflows/large_scale_docking.py
  asapdiscovery-docking/asapdiscovery/docking/workflows/workflows.py
Labels: ready for review, refactor

#590 enable multi-receptor docking
  asapdiscovery-data/asapdiscovery/data/schema_v2/pairs.py
  asapdiscovery-data/asapdiscovery/data/schema_v2/sets.py
  asapdiscovery-data/asapdiscovery/data/selectors/mcs_selector.py
  asapdiscovery-data/asapdiscovery/data/selectors/pairwise_selector.py
  asapdiscovery-data/asapdiscovery/data/selectors/selector.py
  asapdiscovery-data/asapdiscovery/data/selectors/selector_list.py
  asapdiscovery-data/asapdiscovery/data/tests/conftest.py
  asapdiscovery-data/asapdiscovery/data/tests/test_pairs.py
  asapdiscovery-data/asapdiscovery/data/tests/test_selectors.py
  asapdiscovery-data/asapdiscovery/data/tests/test_sets.py
  asapdiscovery-docking/asapdiscovery/docking/cli.py
  asapdiscovery-docking/asapdiscovery/docking/docking_methods.py
  asapdiscovery-docking/asapdiscovery/docking/docking_v2.py
  asapdiscovery-docking/asapdiscovery/docking/openeye.py
  asapdiscovery-docking/asapdiscovery/docking/tests/conftest.py
  asapdiscovery-docking/asapdiscovery/docking/tests/test_docking_v2.py
  asapdiscovery-docking/asapdiscovery/docking/workflows/cross_docking.py
Labels: ready for review, refactor

#640 Add Developer Certificate of Origin
  .github/PULL_REQUEST_TEMPLATE.md
Labels: software
