Repository asapdiscovery/asapdiscovery, pull requests merged in 2024-04, with the labels that each got.

#932 Fix batch training math
  asapdiscovery-ml/asapdiscovery/ml/trainer.py
Labels: ml, tiny

#941 Fix missed import reference updates in asapdiscovery-data.
  asapdiscovery-data/asapdiscovery/data/scripts/download_cdd_data.py
  asapdiscovery-data/asapdiscovery/data/services/cdd/cdd_download.py
Labels: tiny

#942 expose num-poses to cross docking cli
  asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cli.py
  devtools/repo_installer.sh
Labels: software, tiny

#947 Stopgap for no UUID in postera artifact upload
  asapdiscovery-data/asapdiscovery/data/services/postera/postera_uploader.py
  asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/large_scale_docking.py
  asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/small_scale_docking.py
Labels: bug, tiny
