Repository asapdiscovery/asapdiscovery, pull requests merged in 2024-01, with the labels that each got.

#731 Add installer script
  README.md
  devtools/repo_installer.sh
Labels: ready for review, software, tiny

#799 update repo_installer.sh
  devtools/repo_installer.sh
Labels: documentation, ready for review, tiny

#693 Use the overwrite flag instead of deleting the directory by default in workflows
  asapdiscovery-cli/asapdiscovery/cli/cli_args.py
  asapdiscovery-docking/asapdiscovery/docking/cli.py
  asapdiscovery-docking/asapdiscovery/docking/workflows/cross_docking.py
  asapdiscovery-docking/asapdiscovery/docking/workflows/large_scale_docking.py
  asapdiscovery-docking/asapdiscovery/docking/workflows/small_scale_docking.py
Labels: small

#805 fix trainer param gradient handling
  asapdiscovery-ml/asapdiscovery/ml/schema_v2/trainer.py
Labels: bug, ml
